### ISSUE TITLE
'GaussianTSampler is not in the samplers registry'

### ISSUE THREAD

**Issue by briancantwe** [zju3dv/EasyVolcap#13]
Hello!  First, let me compliment you on the amazing work.   I'm truly excited to dig in!  

Running the example on the Readme doc, I've made it to the point of running 3DGS+T using this command:

evc -c configs/exps/gaussiant/gaussiant_${expname}.yaml

but I get this error:

KeyError: 'GaussianTSampler is not in the samplers registry'
*** 'GaussianTSampler is not in the samplers registry'
> /mnt/c/Users/username/documents/github/easyvolcap/easyvolcap/engine/registry.py(121)build_from_cfg()
    119         obj_cls = registry.get(obj_type)
    120         if obj_cls is None:
--> 121             raise KeyError(
    122                 f'{obj_type} is not in the {registry.name} registry')
    123     elif inspect.isclass(obj_type) or inspect.isfunction(obj_type):
    
    I might have missed a step?
    
    Any help appreciated.
    
    Thanks!

**Comment by dendenxu** [comment]
Hi @briancantwe ! Thanks for trying out our code! Usually this means there are some outer level code of `gaussiant_sampler.py` that threw an exception during import, which should be printed at the start of the log. Could you check what that exception is?

**Comment by briancantwe** [comment]
Ah!  Yes, I had missed it.  Pytorch3d wasn't installed.  FIxed that and process completed as expected.  Thank you!
