### ISSUE TITLE
easyvolcap.models.samplers.point_planes_sampler  very slow

### ISSUE THREAD

**Issue by adkAurora** [zju3dv/EasyVolcap#2]
it takes nearly 2hours on v100 to finish this part, is this different on  architecture 75+ gpus？

**Comment by dendenxu** [comment]
Hi @adkAurora, sorry for the late reply. Are you referring to  the process of extracting visual-hulls? Could you please paste a screenshot of the terminal output?

**Comment by adkAurora** [comment]
Sorry for the late reply! 
When I'm training `3DGS-T,` the point_planes_sampler first generates files in the `surfs/` folder. This process is very slow, about 12 minutes per frame.
samplers.point_planes_sampler

```
tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 70. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 70. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
2023-12-21 13:58:26.649892 easyvolcap.models.samplers.point_planes_sampler  Expanding pcds   1% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/102  0:14:26 < -:--:--   ?  it/s p…
                           -> expand_points:
```

**Comment by dendenxu** [comment]
The pre-processing in `expand_points` is used for controlling the number of points by performing marching cubes and then regularize the points to be on the surface. The step should be optional for the `3DGS+T` model and could also be sped up if your input point count is already small enough.

On a 4090, this pre-preprocessing should take around 30s for a 800k-point pointcloud.

1. To skip this step, simply rename `vhulls` to `surfs` or add `model_cfg.sampler_cfg.points_dir=vhulls` to your command (or yaml)
2. To speed up the pre-preprocessing, you need to control the number of input points by controlling the scale of the [`volume_fusion` process](https://github.com/zju3dv/EasyVolcap?tab=readme-ov-file#running-3dgst), either by reducing the render ratio using `val_dataloader_cfg.dataset_cfg.ratio` or the number of depth images to render with `val_dataloader_cfg.dataset_cfg.view_sample`.
