### ISSUE TITLE
unity use

### ISSUE THREAD

**Issue by WangWenShan1** [zju3dv/EasyVolcap#37]
The project is in how to use it in unity, I found the unity_socket_viewer.py script.

**Comment by xbillowy** [comment]
Hi, the [unity_socket_viewer.py](easyvolcap/runners/unity_socket_viewer.py) viewer is used to receive metadata (eg. camera pose) from some Unity SDK, and send rendered images through socket. If you want to use EasyVolcap as a Python rendering backend and communicate with Unity, you can refer to this script.

Let me know if you any further questions~
